"use strict";
const APP_MESSAGES={
	SUCCESS: "Successfully.",
	FOOD_API_ERROR:"Food api error.",
	UNAUTHORIZED:"Unauthorized",
	FORBIDDEN:"Forbidden",
	SUCCESSFULLY_REGISTERD:"Successfully registered.",
	SUCCESSFULLY_SEND_RESET_LINK:"Successfully send reset link in your email Id.",
	SUCCESSFULLY_UPDATED_PASSWORD: "Password has been successfully updated.",
	PROFILE_SUCCESSFULLY_UPDATED:"Profile has been successfully updated.",
	DATABASE_ERROR:"Database error.",
	EMAIL_ALREDAY_VERIFIED: "Email already verified.",
	PLEASE_TRY_AGAIN: "Please try again.",
	EMAIL_ALREDAY_EXIT: "Email already exists.",
	USERNAME_ALREDAY_EXIT: "Username already exists.",
	SECRET_KEY_ALREDAY_EXIT:"Secret key already exists.",
	INVALID_CONTENT_LANGUAGE: "Invalid content language",
	IMPLEMENTATION_ERROR: "Implementation error.",
	DUPLICATE_IS_NOT_ALLOWED: "Duplicate values not allowed on index.",
	INVALID_OBJECT_ID_FROMATE: "Invalid object formate.",
	INVALID_IMAGE_FORMAT: "Invalid image format.",
	INVALID_EMAIL_PASSWORD: "Invalid email or password.",
	INVALID_PASSWORD:"Wrong password",
	EMAIL_OR_USERNAME_REQUIRED:"Email or username required.",
	RESET_LINK_EXPIRED: "Reset link has been expired.",
	RESET_TOKEN_EXPIRED: "Reset token has been expired.",
	INVALID_EMAIL_ID: "Invalid email Id.",
	EMAIL_ID_DOES_NOT_EXISTS: "Email Id does not exists.",
	INVALID_USERNAME_PASSWORD: "Invalid username or password.",
	INVALID_USERNAME: "Invalid username.",
	INVALID_ADMIN_ID: "Invalid admin id.",
	INVALID_INPUT_PARAMETER:"Invalid input parameter.",
	INVALID_TOKEN:"Invalid token provided.",
	IMP_ERROR: "Implementation error.",
	TOKEN_ALREADY_EXPIRED: "Token already expired.",
	TOKEN_NOT_GENRATED_CORRECTLY: "Token not genrated correctly,please try again.",
	ADMIN_BLOCKED:"Admin is blocked.",
	ADMIN_NOT_FOUND:"Admin not found.",
	SAME_PASSWORD_NOT_ALLOWED:"Previous password are not allowed.",
	OLD_PASSWORD_NOT_MATCH:"Old password is wrong.",
	PASSWORD_RESET_LINK_SEND_YOUR_EMAIL:"A link to reset your password has been successfully sent to your email.",
	INVALID_PASSWORD_RESET_TOKEN:"Invalid password reset token.",
	PASSWORD_CHANGED_SUCCESSFULLY:"Password changed sucessfully.",
	INVALID_OTP:"Invalid otp code.",
	OTP_CODE_SEND_YOUR_REGISTER_PHONE_NUMBER:"OTP sent to your registered phone number.",
	OTP_CODE_SEND_YOUR_PHONE_NUMBER:"OTP sent to your phone number.",
	PHONE_NUMBER_ALREADY_EXISTS:"Phone number already exist.",
	PHONE_NUMBER_NOT_EXISTS:"Phone number does not exist.",
	LATEST_VERSION_LESS_THEN_CRITICAL_VERSION:"Latest version should be less than or equal to critical version.",
	USER_NAME_ALREADY_EXISTS:"Username already exists.",
	INVALID_USERNAME_EMAIL:"Invalid email/username.",
	USER_NOT_FOUND:"User does not exists.",
	USER_BLOCKED: "User block successfully.",
	USER_UN_BLOCKED: "User un-block successfully.",
	USER_DELETED: "User deleted successfully.",
	USER_ACTIVE:"User is actived.",
	USER_UN_ACTIVE:"User is actived.",
	USER_REGISTER_SUCCESSFULLY:"User registered successfully.",
	USER_LOGIN_SUCCESSFULLY:"User logged in successfully.",
	USER_LOGOUT_SUCCESSFULLY:"User logged out successfully.",
	USER_PROFILE_UPDATED_SUCCESSFULLY:"User profile updated successfully.",
	USER_CHANGED_PASSWORD_SUCCESSFULLY:"User change password successfully.",
	USER_DELETED_ACCOUNT_SUCCESSFULLY:"User deleted account successfully.",
	FILE_UPLOADED_SUCCESSFULLY:"File successfully.",
	OTP_VERIFIED:"OTP verified.",
	USER_CLEAR_NOTIFICATION:"User clear notification.",
	USER_CLEAR_ALL_NOTIFICATION:"User clear all notification.",
	USER_ADD_SUCCESSFULLY:"User add successfully.",
	USER_PROFILE_UPDATED_SUCCESSFULLY:"User profile updated successfully.",
	USER_DELETED_ACCOUNT_SUCCESSFULLY:"User account deleted successfully.",
	ADMIN_REGISTER_SUCCESSFULLY:"Admin register successfully.",
	DELIVERY_PARTNER_ADDED_SUCCESSFULLY:"Delivery partner added successfully.",
	ADMIN_LOGIN_SUCCESSFULLY:"Admin login successfully.",
	ADMIN_LOGOUT_SUCCESSFULLY:"Admin logout successfully.",
	ADMIN_PROFILE_UPDATED_SUCCESSFULLY:"Admin update profile successfully.",
	DELIVERY_PARTNER_PROFILE_UPDATED_SUCCESSFULLY:"Delivery partner update profile successfully.",
	BUSINESS_PARTNER_PROFILE_UPDATED_SUCCESSFULLY:"Business partner update profile successfully.",
	ADMIN_CHANGED_PASSWORD_SUCCESSFULLY:"Admin changed password successfully.",
	ADMIN_DELETED_ACCOUNT_SUCCESSFULLY:"Admin deleted account successfully.",
	FILE_UPLOADED_SUCCESSFULLY:"File upload successfully.",
	ADMIN_CLEAR_NOTIFICATION:"Admin clear notification successfully.",
	ADMIN_CLEAR_ALL_NOTIFICATION:"Admin clear all notification successfully.",
	ADMIN_ADD_ALGORITHEM_SUCCESSFULLY:"Admin add algorithm successfully.",
	ADMIN_UPDATE_ALGORITHEM_SUCCESSFULLY:"Admin update algorithm successfully.",
	ADMIN_DELETED_ALGORITHEM_SUCCESSFULLY:"Admin deleted algorithm successfully.",
	APP_VERSION_ADDSUCCESFULLY:"Admin set app version sucessfully.",
	DATA_NOT_FOUND:"Data not found.",
	NOTIFICATION_SEND_TO_USER:"Notification send to user successfully.",
	QUERY_SUBMITTED:"Your query submitted successfully.",
	DRIVER_REGISTER_SUCCESSFULLY:"Driver registered successfully.",
	DRIVER_LOGIN_SUCCESSFULLY:"Driver logged in successfully.",
	DRIVER_LOGOUT_SUCCESSFULLY:"Driver logged out successfully.",
	DRIVER_PROFILE_UPDATED_SUCCESSFULLY:"Driver profile updated successfully.",
	DRIVER_CHANGED_PASSWORD_SUCCESSFULLY:"Driver change password successfully.",
	DRIVER_ADD_SUCCESSFULLY:"Driver add successfully.",
	DRIVER_BLOCKED:"Driver block successfully.",
	DRIVER_UN_BLOCKED:"Driver Un-block successfully.",
	DRIVER_DELETED:"Driver deleted successfully.",
	DRIVER_ACTIVE:"Driver active successfully.",
	DRIVER_UN_ACTIVE:"Driver un-active successfully.",
	DRIVER_NOT_FOUND:"Driver not found.",
	ZONE_ALREADY_EXIST:"Zone already exists.",
	ZONE_ADDED_SUCCESSFULLY:"Zone added successfully.",
	ZONE_DELETED_SUCCESSFULLY:'Zone deleted successfully.',
	ZONE_UPDATED_SUCCESSFULLY:'Zone updated successfully.',
	GEOFENCE_ADDED_SUCCESSFULLY:"Geofence added successfully.",
	FIRST_YOU_ASSIGN_GEOFENCE_AND_ZONE:"First you assign zone and geofence to driver then try to activate.",
	VEHICLE_CATEGORY_DELETED_SUCCESSFULLY:"vehicle category deleted successfully.",
	VEHICLE_CATEGORY_ALREADY_EXIST:"vehicle category already exists.",
	VEHICLE_CATEGORY_UPDATE_SUCCESSFULLY:"vehicle category updated successfully.",
	VEHICLE_CATEGORY_ADDED_SUCCESSFULLY:"vehicle category added successfully.",
	DOCUMENT_ALREADY_EXIST:'Document name already exists.',
	DOCUMENT_ADDED_SUCCESSFULLY:'Document added successfully.',
	DOCUMENT_UPDATE_SUCCESSFULLY:'Document updated successfully.',
	DOCUMENT_DELETED_SUCCESSFULLY:'Document deleted successfully.',
	PAYMENT_GATEWEY_ALREADY_EXIST:'Payment gateway already exists.',
	PAYMENT_GATEWEY_ADDED_SUCCESSFULLY:'Payment gateway added successfully.',
	PAYMENT_GATEWEY_UPDATE_SUCCESSFULLY:'Payment gateway updated successfully.',
	PAYMENT_GATEWEY_ACTIVE:'Payment gateway is active successfully.',
	PAYMENT_GATEWEY_UN_ACTIVE:'Payment gateway is un-active successfully.',
	LANGUAGE_ALREADY_EXIST:'Language already exists.',
	LANGUAGE_ADDED_SUCCESSFULLY:'Language added successfully.',
	LANGUAGE_UPDATE_SUCCESSFULLY:'Language updated successfully.',
	LANGUAGE_ACTIVE:'Language is active successfully.',
	LANGUAGE_UN_ACTIVE:'Language is un-active successfully',
	DELIVERY_PARTNER_ACCEPT:'Delivery partner accepted account.',
    DELIVERY_PARTNER_REJECT:'Delivery partner accepted reject.',
    BUSINESS_PARTNER_ACCEPT:'Business partner accepted account.',
    BUSINESS_PARTNER_REJECT:'Business partner accepted reject.',
    DRIVER_ACCEPT:'Driver accepted account.',
	DRIVER_REJECT:'Driver accepted reject.',
	CMS_ADD_SUCCESSFULLY:'CMS add successfully',
	CMS_UPDATED_SUCCESSFULLY:'CMS updated successfully',
	GEOFENCE_NAME_ALREADY_EXISTS:'Geofence name already exists.',
	GEOFENCE_DELETED_SUCCESSFULLY:'Geofence deleted successfully.',
	GEOFENCE_UPDATED_SUCCESSFULLY:'Geofence updated successfully.',
	WRONG_GEOFENCE_COORDINATES:'Wrong geo-fence co-ordinated.',
	DELIVERY_PARTNER_DELETED:'Delivery partner deleted successfully.',
	BUSINESS_PARTNER_DELETED:'Business partner deleted successfully.',
	ADMIN_DELETED:'Admin deleted successfully.',
	BACK_DATE_NOT_ALLOWED:'Back date is not allowed.',
	REFERRAL_CODE_USED:'Referral code already used.',
	INVALID_REFERRAL_CODE:'Invalid referral code.',
	PROMO_CODE_ALREADY_INUSED:'Promo code already used.',
	PROMO_CODE_EXPIRED:'Promo code expired.',
	PROMO_CODE_ALREADY_EXISTS:'Promo code already exists.',
	PROMO_CODE_BACK_DATE_NOT_ALLOWED:'Promo code back date not allowed.',
	PROMO_CODE_ADDED:'Promo code add successfully.',
	PROMO_CODE_EDIED:'Promo code edit successfully.',
	PROMO_CODE_DELEED:'Promo code deleted successfully.',
	PROMO_CODE_BLOCKED:'Promo code blocked successfully.',
	PROMO_CODE_UN_BLOCKED:'Promo code un-blocked successfully.',
	DISCOUNT_ADDED:'Discount add successfully.',
	DISCOUNT_EDIED:'Discount edit successfully.',
	DISCOUNT_DELEED:'Discount deleted successfully.',
	INVALID_PROMO_CODE:'Invalid promo code.',
	DISCOUNT_ACTIVE:'Discount is active successfully.',
	DISCOUNT_UN_ACTIVE:'Discount is in-active successfully.',
	NO_VEHICLE_FOUND:'There is no vehicle found for this place.',
	ADDRESS_DELETED_SUCCESSFULLY:"Address deleted successfully.",
	ADDRESS_EDIT_SUCCESSFULLY:"Address edit successfully.",
	ADDRESS_ADD_SUCCESSFULLY:"Address add successfully.",
	VEHICLE_CATEGORY_NO_LONGER_AVAILABLE:"Vehicle category No longer avaliable.",
	PACKAGE_NO_LONGER_AVAILABLE:"Package No longer avaliable.",
	FIRST_NAME_VALIDATION_ERROR: "First name should not contain special characters.",
	LAST_NAME_VALIDATION_ERROR: "Last name should not contain special characters.",
	PHONE_NUMBER_VALIDATION_ERROR: "Phone number should only contain numbers.",
	COUNTRY_CODE_VALIDATION_ERROR: "Country code length must be at least 2 characters long.",
	DRIVER_TYPE_ERROR: "You don't have privileges to change your driver type",
	BOOKING_ALREADY_ACCEPTED: "This booking has been accepted by another driver",
	INVALID_BOOKING_ID: "Invalid booking ID.",
	BOOKING_CANCELLED: "Booking cancelled successfully.",
	BOOKING_ALREADY_CANCELLED: "Booking is already cancelled.",
	LEADS_FETCHED_SUCCESSFULLY: "Leads fetched successfully.",
	DRIVER_ADD_FAVOURITE_SUCCESSFULLY: "Driver add favourite successfully.",
	DRIVER_REMOVE_FAVOURITE_SUCCESSFULLY: "Driver remove favourite successfully.",
	PHONE_NUMBER_NOT_MATCHED_EXISTS: "Phone number not matched.",
	DRIVER_NOT_FOUND: "Driver not found.",
	Driver_BLOCKED: "Driver blocked.",
	CUSTOMER_CHANGED_PASSWORD_SUCCESSFULLY: "Customer changed password successfully.",
	DRIVER_CHANGED_PASSWORD_SUCCESSFULLY: "Driver changed password successfully.",
	OTP_CODE_SEND_YOUR_PHONE_NUMBER:"Otp code send your phone number.",
	CONFIRM_PASSWORD_NOT_MATCHED_WITH_PASSWORD:"Confirm password not matched with current password. ",
	VEHICLE_NUMBER_ALREADY_EXISTS: "Vehicle number already exist.",
	ADD_VEHICLE_DETAILS_SUCCESSFULLY: "Add vehical details successfully."
};
module.exports = {
	APP_MESSAGES:APP_MESSAGES
};